# Generated by Django 4.1.2 on 2022-10-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo", old_name="state", new_name="is_done",
        ),
    ]
